config/routes.rb
Todo::Application.routes.draw do
  resources :todo_items
  root :to => 'todo_items#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  attr_accessible :completed, :deleted, :due_at, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.where(:completed => false, :deleted => false).order(:updated_at)
    @completed_items = TodoItem.where(:completed => true, :deleted => false).order(:updated_at)
    @todo_item = TodoItem.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todo_items + @completed_items }
      format.xml {render xml: @todo_items + @completed_items }
    end
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(params[:todo_item])

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to root_path, notice: 'Todo item was successfully created.' }
        format.json { render json: @todo_item, status: :created, location: @todo_item }
      else
        format.html { render action: "new" }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_items/1
  # PUT /todo_items/1.json
  def update
    @todo_item = TodoItem.find(params[:id])

    respond_to do |format|
      if @todo_item.update_attributes(params[:todo_item])
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item = TodoItem.find(params[:id])
    @todo_item.destroy

    respond_to do |format|
      format.html { redirect_to todo_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
  def svg_object(name)
    # Why the extra span, bro?
    # Because we want to be able to wrap it in a link.
    # See: http://stackoverflow.com/a/12732030/209190
    "<span><object data=\"#{image_path(name + '.svg')}\" type=\"image/svg+xml\">#{image_tag(name + '.png')}</object></span>".html_safe
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield
    %footer
      Trash icon by
      = succeed "." do
        %a{:href => "http://thenounproject.com/DmitryBaranovskiy/"} Dmitry Baranovskiy
      Thanks Dmitry!

app/views/todo_items/_list.html.haml
%ol{:id => list_name}
  - list.each do |todo_item|
    %li{"data-id" => todo_item.id}
      %span.item_checkbox
        = check_box_tag(nil, nil, todo_item.completed)
      %span.item_name
        = todo_item.name
      %time.item_due_at{:datetime => todo_item.due_at.iso8601}
        = todo_item.due_at.strftime("%A, %B %e, %Y")
      %span.item_delete
        = link_to svg_object('trash'), todo_item, method: :delete, data: { confirm: 'Are you sure?' }

app/views/todo_items/index.html.haml
%h1 Create a new TODO
.spinner.hidden
  = image_tag("big-roller.gif")
%p.error.hidden
  Server is not working. Try again later.
= form_for(@todo_item) do |f|
  - if @todo_item.errors.any?
    #error_explanation
      %h2
        = pluralize(@todo_item.errors.count, "error")
        prohibited this todo_item from being saved:
      %ul
        - @todo_item.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :due_at
    = f.date_select :due_at
  .actions
    = f.submit "Add item"
%h2 Listing TODOs
= render :partial => 'list', :locals => {:list => @todo_items, :list_name => 'todo'}
%h2 Completed TODOs
= render :partial => 'list', :locals => {:list => @completed_items, :list_name => 'completed'}

app/views/todo_items/new.html.erb
<h1>New todo_item</h1>

<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_at %><br />
    <%= f.datetime_select :due_at %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h1>Listing todo_items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Due at</th>
    <th>Completed</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.name %></td>
    <td><%= todo_item.due_at %></td>
    <td><%= todo_item.completed %></td>
    <td><%= todo_item.deleted %></td>
    <td><%= link_to 'Show', todo_item %></td>
    <td><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
    <td><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>